(function(){const fallback=[
{id:'simon',label:'Simon · Street',title:'Interactive street',owner:'Simon · Visual interface',purpose:'See how visible street interventions change the character of a place.',boundary:'A concept view, not a feasibility assessment.',url:'../wrapper/frontend/v1/index.html'},
{id:'andy',label:'Andy · Map',title:'Location explorer',owner:'Andy · Data and mapping',purpose:'Move from city-scale signals to a candidate place worth investigating.',boundary:'A screening signal is not a site recommendation.',url:'contributions/andy/current/index.html'},
{id:'bala',label:'Bala · Learn',title:'Sponge-city explainers',owner:'Bala · Learning experience',purpose:'Understand the measures, mechanisms and language behind a sponge city.',boundary:'Educational context does not establish local performance.',url:'../explainer-videos-context/playground.html'},
{id:'xray',label:'Street X-Ray',title:'Street X-Ray',owner:'Achim · Evidence workflow',purpose:'Expose hypotheses, blockers, gatekeepers and missing evidence.',boundary:'Visible space is not automatically buildable space.',url:'../wrapper/street-xray/index.html'},
{id:'rainwalk',label:'Rain Walk',title:'Rain Walk',owner:'Achim + residents · Observation',purpose:'Turn local observation into a provenance-bearing field note.',boundary:'Surface observation cannot reveal underground conditions.',url:'../wrapper/street-workspace/public/rain-walk/index.html'},
{id:'charter',label:'Data Charter',title:'Data Charter',owner:'Team · Evidence classification',purpose:'Mark what is known, derived, assumed, modelled, restricted or missing.',boundary:'A relevant dataset is not automatically valid for a decision.',url:'stage.html#classify'},
{id:'case',label:'Connected Case',title:'Connected Case',owner:'Team · Next action',purpose:'Connect claims, gaps, gatekeepers and actions into one bounded case.',boundary:'The current state is investigation, not a recommendation to construct.',url:'stage.html#decide'}];let modules=fallback;const tabs=document.querySelector('#module-tabs'),frame=document.querySelector('#module-frame');
function select(i,focus){const m=modules[i];tabs.querySelectorAll('button').forEach((b,n)=>{b.setAttribute('aria-selected',String(n===i));b.tabIndex=n===i?0:-1;if(n===i&&focus)b.focus()});document.querySelector('#module-owner').textContent=m.owner;document.querySelector('#module-title').textContent=m.title;document.querySelector('#module-purpose').textContent=m.purpose;document.querySelector('#module-boundary').textContent=m.boundary;document.querySelector('#module-open').href=m.url;frame.src=m.url;frame.title=m.title+' live module'}
function render(){tabs.innerHTML=modules.map((m,i)=>`<button type="button" role="tab" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-i="${i}">${m.label}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>{b.onclick=()=>select(+b.dataset.i,false);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=+b.dataset.i,n=e.key==='Home'?0:e.key==='End'?modules.length-1:(i+(e.key==='ArrowRight'?1:-1)+modules.length)%modules.length;select(n,true)}});select(0,false)}
fetch('data/showcase-manifest.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(m=>{if(m.modules?.length!==7)throw Error('modules');modules=m.modules;render()}).catch(()=>render())})();
